// src/entities/user/constants/errorCodes.ts
export const USER_ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
};
